apps/api/urls.py
from django.urls import path
from apps.api import views

urlpatterns = [
    path(r'clients/', views.clients, name='clients'),
    path(r'clients/emails/', views.client_emails, name='client_emails'),
    path(r'clients/phone/', views.client_phones, name='client_phones'),
    path(r'headquarters/', views.headquarters, name='headquarters'),
    path(r'rooms/', views.rooms, name='rooms'),
    path(r'events/', views.events, name='events'),
    path(r'events/confirm/', views.confirm_event, name='confirm_event'),
    path(r'events/summary/', views.events_summary, name='events_summary'),
]

apps/core/urls.py
from django.urls import path
from apps.core import views

urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'clients/', views.clients, name='clients'),
    path(r'clients/add/', views.create_client, name='create_client'),
    path(r'clients/mod/<int:_id>/', views.modify_client, name='modify_client'),
    path(r'rooms/', views.rooms, name='rooms'),
    path(r'rooms/add/', views.create_room, name='create_room'),
    path(r'rooms/addHQ/', views.create_hq, name='create_headquarter'),
    path(r'events/', views.events, name='events'),
    path(r'events/add/', views.create_event, name='create_event'),
]

apps/users/urls.py
from django.urls import path
from apps.users import views
from apps.users.views import api

urlpatterns = [
	path(r'login/', views.login_page, name='login'),
	path(r'logout/', views.logout, name='logout'),
	path(r'install/', views.install_users, name='install'),
	path(r'admin/', views.admin_users, name='admin'),
	path(r'admin/add/', views.create_user, name='create'),
	path(r'changePassword/', views.change_password, name='change_password'),

	# Api views
	path(r'api/login/', api.login, name='api_login'),
	path(r'api/install/', api.install_users, name='api_install'),
	path(r'api/admin/', api.alter_user_admin, name='api_alter_user_admin'),
	path(r'api/create/', api.create_user, name='api_create'),
	path(r'api/password/', api.change_password, name='api_change_password'),
]

bussines_rooms/urls.py
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path(r'api/', include(('apps.api.urls', 'apps.api'), namespace='api')),
    path(r'', include(('apps.core.urls', 'apps.core'), namespace='core')),
    path(r'users/', include(('apps.users.urls', 'apps.users'), namespace='users')),
]

templates/admin.html
{% extends "commons/base.html" %}

{% block title %}Manage users{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="text-center">Created users</h1>
		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">Identification</th>
					<th scope="col">Full Name</th>
					<th scope="col">Is Admin</th>
					<th scope="col">Change Admin</th>
				</tr>
			</thead>
			<tbody>
				{% for user in users %}
					<tr>
					{% if user.its_me %}
					<td><abbr title="It's you">{{ user.identification }}</abbr></td>
					{% else %}
					<td>{{ user.identification }}</td>
					{% endif %}
						
						<td>{{ user.full_name }}</td>
						<td><input
							type="checkbox"
							{% if user.is_admin %}
								checked="true"
							{% endif %}
							id="check-{{ user.id }}"
							disabled="true"
							class="for-check-input"
						></td>
						<td>
							{% if user.is_admin %}
								<button
									class="btn btn-danger admin-action"
									data-id="{{ user.id }}"
									data-admin="False"
									{% if user.its_me %}
										disabled="true"
									{% endif %}
								>Remove from administrators</button>
							{% else %}
								<button class="btn btn-success admin-action" data-id="{{ user.id }}" data-admin="True">Add to administrators</button>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
			{% if len_users >= 100 %}
				<tfoot>
					<tr>
						<th scope="col">Identification</th>
						<th scope="col">Full Name</th>
						<th scope="col">Is Admin</th>
						<th scope="col">Change Admin</th>
					</tr>
				</tfoot>
			{% endif %}
		</table>
		<hr>
		<a href="{% url 'users:create' %}" class="btn btn-link">Create an user</a>
	</div>
	{% csrf_token %}
{% endblock %}

{% block scripts %}
	<script type="module">
		import {onLoad,bAlert} from '/static/js/utils.mjs';
		onLoad(() => {
			let csfrToken = document.querySelector('input[name=csrfmiddlewaretoken]').value;

			document.querySelectorAll('button.admin-action').forEach(el => {
				el.addEventListener('click', async () => {
					if (!confirm('Are you sure to do this action?')) {
						return null
					}

					let req = await fetch("{% url 'users:api_alter_user_admin' %}", {
						method: 'PUT',
						headers: new Headers({
							'Content-Type': 'application/json',
							'X-CSRFToken': csfrToken,
						}),
						body: JSON.stringify({
							id: parseInt(el.dataset.id),
							admin: el.dataset.admin == 'True'
						})
					}).then(out => out.json())

					if (req.error !== undefined) {
						return alerts.appendChild(bAlert('danger', `Error: ${req.error}`));
					}

					document.getElementById(`check-${el.dataset.id}`).checked = el.dataset.admin == 'True'
					if (el.dataset.admin == 'True') {
						el.classList.replace('btn-success', 'btn-danger')
						el.innerText = 'Remove from administrators'
						el.dataset.admin = 'False'
					} else {
						el.classList.replace('btn-danger', 'btn-success')
						el.innerText = 'Add to administrators'
						el.dataset.admin = 'True'
					}
				})
			})
		})
	</script>
{% endblock %}

templates/change_password.html
{% extends "commons/base.html" %}

{% block title %}LogIn{% endblock %}

{% block body %}
	<div id="alerts"></div>
	<div class="row g-0 gy-5">
		<div class="col-12"></div>
		<div class="col-sm-1 col-md-3 col-lg-4"></div>
		<div class="col-sm-10 col-md-6 col-lg-4">
			<form>
				{% csrf_token %}
				<div class="mb-3">
					<label for="actualpassword" class="form-label">Actual Password</label>
					<input type="password" class="form-control" name="actualpassword">
				</div>
				<hr>
				<div class="mb-3">
					<label for="newpassword" class="form-label">New Password</label>
					<input type="password" class="form-control" name="newpassword">
				</div>
				<div class="mb-3">
					<label for="newpassword2" class="form-label">Confirm New Password</label>
					<input type="password" class="form-control" name="newpassword2">
				</div>

				<button class="btn btn-warning" name="send" type="submit">Change</button>
			</form>
		</div>
	</div>
{% endblock %}

{% block scripts %}
	<script type="module">
		import {bAlert, disableForm, onLoad} from '/static/js/utils.mjs';

		onLoad(() => {
			const form = document.querySelector('form');
			const alerts = document.getElementById('alerts');

			disableForm(form);

			form.send.addEventListener('click', async () => {
				if (form.actualpassword.value == '' || form.newpassword.value == '' || form.newpassword2.value == '') {
					return alerts.appendChild(bAlert('danger', 'All fields are required'));
				}

				if (form.newpassword.value  != form.newpassword2.value) {
					return alerts.appendChild(bAlert('danger', 'The new password doesn\'t match'));
				}

				let notice = bAlert('secondary', 'Sending request...');
				alerts.appendChild(notice);

				const req = await fetch("{% url 'users:api_change_password' %}", {
					method: 'PUT',
					headers: new Headers({
						'Content-Type': 'application/json',
						'X-CSRFToken': form.csrfmiddlewaretoken.value
					}),
					body: JSON.stringify({
						password: form.actualpassword.value,
						newPassword: form.newpassword.value
					})
				}).then(out => out.json());

				notice.children[1].click();
				if (req.error !== undefined) {
					return alerts.appendChild(bAlert('danger', `Error: ${req.error}`));
				}

				window.location.replace("{% url 'core:home' %}");
			});
		});
	</script>
{% endblock %}

templates/events.html
{% extends "commons/base.html" %}

{% block title %}Events{% endblock %}

{% block body %}
	{% include "core/navbar.html" %}
	<div class="container" style="margin-top: 1em;">
		<a href="{% url 'core:create_event' %}" class="btn btn-primary">Create</a>
		<hr>
		<div id="events">
			<h1 v-if="!loaded" class="text-center">Loading...</h1>
			<div v-else>
				<div class="input-group">
					<input type="date" v-model="from" class="form-control">
					<input type="date" v-model="to" class="form-control">
				</div>
				<div class="bm-0 form-check">
					<input type="checkbox" v-model="onlyConfirmed" class="form-check-input">
					<label class="form-check-label">Only Confirmed</label>
				</div>
				<br>
				<button v-on:click="refresh" class="btn btn-secondary">Filter</button>
				<hr>
				<h1 v-if="events.length == 0">No events created.</h1>
				<table v-else class="table table-hover table-sm">
					<thead>
						<tr>
							<th>Client Name</th>
							<th>Identification</th>
							<th>Phones</th>
							<th>Location</th>
							<th>Location Detail</th>
							<th>People Count</th>
							<th>Event Type</th>
							<th>Event At</th>
							<th>Check</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="event in events">
							<td>[[ event.name ]]</td>
							<td>[[ event.identification ]]</td>
							<td>
								<ul class="list-group">
									<li v-for="phone in event.phones" class="list-group-item">[[ phone ]]</li>
								</ul>
							</td>
							<td>[[ event.country ]], [[ event.state ]], [[ event.city ]]</td>
							<td>
								<textarea rows="2" readonly="true" class="form-control" v-model="event.locationDetail"></textarea>
							</td>
							<td>[[ event.peopleCount ]]</td>
							<td>[[ event.eventType ]]</td>
							<td>[[ event.eventAt ]]</td>
							<td><input type="checkbox" v-bind:checked="event.isConfirmed" disabled="true"></td>
							<td>
								<button v-on:click="changeState(event.id, !event.isConfirmed)" class="btn btn-secondary">
									[[ (event.isConfirmed)? 'Cancel' : 'Confirm' ]]
								</button>
								<button v-on:click="del(event.id)" class="btn btn-danger">Delete</button>
							</td>
						</tr>
					</tbody>
					<tfoot v-show="events.length > 100">
						<tr>
							<th>Client Name</th>
							<th>Identification</th>
							<th>Phones</th>
							<th>Location</th>
							<th>Location Detail</th>
							<th>People Count</th>
							<th>Event Type</th>
							<th>Event At</th>
							<th>Check</th>
							<th>Actions</th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
	<script src="https://unpkg.com/vue@3.0.11/dist/vue.global.js"></script>
	<script type="module">
		Vue.createApp({
			delimiters: ['[[', ']]'],
			setup() {
				const from = Vue.ref('');
				const to = Vue.ref('');
				const onlyConfirmed = Vue.ref(false);
				const events = Vue.ref([]);
				const loaded = Vue.ref(false);
				const csfrToken = '{{ csrf_token }}';

				const refresh = async () => {
					loaded.value = false;
					let query = [];

					if (onlyConfirmed.value) {
						query.push('confirmed=yes');
					}

					if (from.value != '') {
						query.push(`from=${encodeURI(new Date(from.value).toISOString())}`);
						if (to.value != '') {
							query.push(`to=${encodeURI(new Date(to.value).toISOString())}`);
						} else {
							query.push(`to=max`);
						}
					}

					events.value = await fetch(`{% url 'api:events_summary' %}?${query.join('&')}`)
						.then(out => out.json());

					events.value = events.value.map(el => {
						el.eventAt = new Date(el.eventAt).toLocaleDateString()
						return el;
					});

					loaded.value = true;
				}

				const del = async (id) => {
					if (!confirm('Are you sure to do this action?')) {
						return null
					}
					
					await fetch("{% url 'api:events' %}", {
						method: 'DELETE',
						headers: new Headers({
							'Content-Type': 'application/json',
							'X-CSRFToken': csfrToken,
						}),
						body: JSON.stringify({
							id
						})
					});

					refresh();
				}

				const changeState = async (id, state) => {
					if (!confirm('Are you sure to do this action?')) {
						return null
					}

					await fetch("{% url 'api:confirm_event' %}", {
						method: 'PUT',
						headers: new Headers({
							'Content-Type': 'application/json',
							'X-CSRFToken': csfrToken,
						}),
						body: JSON.stringify({
							id,
							state
						})
					});
					
					refresh();
				}

				Vue.onMounted(() => refresh())

				return {
					from,
					to,
					onlyConfirmed,
					loaded,
					events,
					refresh,
					changeState,
					del
				}
			}
		}).mount('#events')
	</script>
{% endblock %}

templates/index.html
{% extends "commons/base.html" %}

{% block title %}Home{% endblock %}

{% block body %}
	{% include "core/navbar.html" %}
	<div class="container card" style="margin-top: 1em;">
		<div class="card-body">
			<h3>
				Welcome, {{ user_data.full_name }}
				{% if user_data.admin %}
					<span class="badge bg-info">Admin</span>
				{% endif %}
			</h3>
			<p>
				Identification: <code>{{ user_data.identification }}</code>
			</p>
		</div>
	</div>
{% endblock %}

templates/modify_client.html
{% extends "commons/base.html" %}

{% block title %}Modify Client{% endblock %}

{% block body %}
	{% include "core/navbar.html" %}
	<div id="alerts"></div>
	<div class="row g-0 gy-5">
		<div class="col-12"></div>
		<div class="col-sm-1 col-md-3 col-lg-4"></div>
		<div class="col-sm-10 col-md-6 col-lg-4">
			<form>
				{% csrf_token %}
				<input type="hidden" name="id" value="{{ client.id }}">
				<div class="mb-3">
					<label for="identification" class="form-label">Identification Number</label>
					<div class="input-group">
						<input type="text" class="form-control" inputmode="numeric" placeholder="Number" value="{{ client.identification }}" disabled="true">
						<span class="input-group-text">-</span>
						<input type="text" class="form-control" inputmode="numeric" placeholder="Verification Digit" value="{{ client.identification_vd }}" disabled="true">
					</div>
				</div>
				<div class="mb-3">
					<label for="firstname" class="form-label">Full Name</label>
					<div class="input-group">
						<input type="text" class="form-control capital" name="firstname" value="{{ client.first_name }}" placeholder="First Name">
						<input type="text" class="form-control capital" name="secondname" value="{{ client.second_name }}" placeholder="Second Name">
					</div>
					<div class="input-group">
						<input type="text" class="form-control capital" name="firstlastname"  value="{{ client.first_last_name }}" placeholder="First Last Name">
						<input type="text" class="form-control capital" name="secondlastname" value="{{ client.second_last_name }}" placeholder="Second Last Name">
					</div>
				</div>
				<div class="mb-3">
					<label for="age" class="form-label">Age</label>
					<select name="age" class="form-control">
						{% for age in ages %}
							<option
								value="{{ age }}"
								{% if client.age == age %}
									selected="true"
								{% endif %}
							>{{ age }}</option>
						{% endfor %}
					</select>
				</div>
				<div class="mb-3">
					<label for="country" class="form-label">Location</label>
					<select name="country" class="form-control">
						<option value="" disabled="true" hidden="true">Select a Country...</option>
					</select>
					<br>
					<select name="state" class="form-control">
						<option value="" disabled="true" hidden="true">Select a State...</option>
					</select>
					<br>
					<select name="city" class="form-control">
						<option value="" disabled="true" hidden="true">Select a City...</option>
					</select>
				</div>
				<div class="mb-3">
					<label for="phones" class="form-label">Phones</label>
					<div id="phones">
						{% for phone in phones %}
							<div class="input-group" style="margin-bottom: 0.5em;">
								<input type="text" class="form-control persistent" inputmode="numeric" value="{{ phone.reg_code }}" placeholder="Regional Code"  disabled="true">
								<input type="text" class="form-control persistent" inputmode="numeric" value="{{ phone.number }}"  placeholder="Phone Number" disabled="true">
							</div>
						{% endfor %}
					</div>
					<button type="button" class="btn btn-success" id="addPhone" style="min-width: 100%;">Add phone</button>
				</div>

				<div class="mb-3">
					<label for="email" class="form-label">Emails</label>
					<div id="emails">
						{% for email in emails %}
							<div class="input-group" style="margin-bottom: 0.5em;">
								<input type="text" class="form-control persistent" inputmode="email" value="{{ email }}" placeholder="Email" disabled="true">
							</div>
						{% endfor %}
					</div>
					<button type="button" class="btn btn-success" id="addEmail" style="min-width: 100%;">Add email</button>
				</div>

				<button class="btn btn-primary" name="send" type="submit">Modify</button>
			</form>
		</div>
	</div>
{% endblock %}

{% block scripts %}
	<script type="module">
		import {bAlert, disableForm, onLoad, emailRegex} from '/static/js/utils.mjs';
		import {getCountries, getStates, getCities} from '/static/js/geoApi.mjs';

		var defaultPhoneCode = '';

		const implodeInput = (evt) => evt.target.parentElement.remove();
		const onlyNumbers = (evt) => {
			evt.target.value = evt.target.value.replace(/[^\-0-9]/g, '');
		};
		const capitalize = (evt) => {
			evt.target.value = evt.target.value.replace(/[^a-z\ ]/ig, '')
				.split(' ')
				.map(txt => txt.substr(0, 1).toUpperCase() + txt.substr(1).toLowerCase())
				.join(' ');
		};
		const persistentInput = (evt) => {
			evt.target.setAttribute('value', evt.target.value)
		};

		onLoad(() => {
			const form = document.querySelector('form');
			const countriesMap = {};

			disableForm(form);

			document.querySelectorAll('button.implode').forEach(el => {
				el.addEventListener('click', implodeInput);
			});

			document.querySelectorAll('input.capital').forEach(el => {
				el.addEventListener('input', capitalize);
			});

			document.querySelectorAll('input.persistent').forEach(el => {
				el.addEventListener('input', persistentInput);
			});

			document.querySelectorAll('input[inputmode="numeric"]').forEach(el => {
				el.addEventListener('input', onlyNumbers);
			});

			document.getElementById('addPhone').addEventListener('click', () => {
				document.getElementById('phones').innerHTML += `<div class="input-group" style="margin-bottom: 0.5em;">
					<input type="text" value="${defaultPhoneCode}" class="form-control persistent" inputmode="numeric" placeholder="Regional Code" name="regcode">
					<input type="text" class="form-control persistent" inputmode="numeric" placeholder="Phone Number" name="phone">
					<button class="btn btn-danger implode" type="button">Remove</button>
				</div>`;

				document.querySelectorAll('button.implode').forEach(el => {
					el.addEventListener('click', implodeInput)
				});
				document.querySelectorAll('input[inputmode="numeric"]').forEach(el => {
					el.addEventListener('input', onlyNumbers)
				});
				document.querySelectorAll('input.persistent').forEach(el => {
					el.addEventListener('input', persistentInput);
				});
			});

			document.getElementById('addEmail').addEventListener('click', () => {
				document.getElementById('emails').innerHTML += `<div class="input-group" style="margin-bottom: 0.5em;">
					<input type="text" class="form-control persistent" inputmode="email" placeholder="Email" name="email">
					<button class="btn btn-danger implode" type="button">Remove</button>
				</div>`;

				document.querySelectorAll('button.implode').forEach(el => {
					el.addEventListener('click', implodeInput)
				});
				document.querySelectorAll('input.persistent').forEach(el => {
					el.addEventListener('input', persistentInput);
				});
			});

			const prepareCity = async (state) => {
				let cities = await getCities(state);

				form.city.innerHTML = '<option value="" disabled="true" hidden="true">Select a City...</option>';
				cities.map(city => {
					const el = document.createElement('option');

					el.value = city.city_name;
					el.innerText = city.city_name;

					if (city.city_name == '{{ client.city }}') {
						el.selected = true;
					}

					return el;
				}).forEach(el => {
					form.city.appendChild(el);
				});
			}

			const prepareState = async (country) => {
				let states = await getStates(country);
				form.state.innerHTML = '<option value="" disabled="true" hidden="true">Select a State...</option>';

				states.map(state => {
					const el = document.createElement('option');

					el.value = state.state_name;
					el.innerText = state.state_name;

					if (state.state_name == '{{ client.state }}') {
						el.selected = true;
					}

					return el;
				}).forEach(el => {
					form.state.appendChild(el);
				});

				if (form.state.dataset.createdEvent !== '1') {
					form.state.dataset.createdEvent = '1';
					form.state.addEventListener('change', () => {
						prepareCity(form.state.value)
					});
				}
			}

			getCountries().then(countries => {
				countries.map(country => {
					const el = document.createElement('option');

					el.value = country.country_short_name;
					el.innerText = country.country_name;

					if (country.country_short_name == '{{ client.country }}') {
						el.selected = true;
					}

					countriesMap[country.country_short_name] = {
						name: country.country_name,
						regCode: country.country_phone_code
					};

					return el;
				}).forEach(el => {
					form.country.appendChild(el)
				})
			}).then(() => {
				prepareState(countriesMap['{{ client.country }}'].name)
				prepareCity('{{ client.state }}')
				form.country.addEventListener('change', evt => {
					defaultPhoneCode = countriesMap[form.country.value].regCode;
					prepareState(countriesMap[form.country.value].name);
				})
			});

			form.send.addEventListener('click', async () => {
				function getPhones() {
					if (form.phone === undefined) {
						return [];
					} else if (form.phone instanceof HTMLElement) {
						return [`${form.regcode.value} ${form.phone.value}`];
					}

					let res = [];
					for (var i = 0; i < form.phone.length; i++) {
						res.push(`${form.regcode[i].value} ${form.phone[i].value}`);
					}
					return res;
				}

				function getEmails() {
					if (form.email === undefined) {
						return [];
					} else if (form.email instanceof HTMLElement) {
						return [form.email.value];
					}

					let res = [];
					for (var i = 0; i < form.email.length; i++) {
						res.push(form.email[i].value);
					}
					return res;
				}

				if (
					form.firstname.value == '' ||
					form.firstlastname.value == '' ||
					form.age.value == '' ||
					form.country.value == '' ||
					form.state.value == '' ||
					form.city.value == ''
				) {
					return alerts.appendChild(bAlert('danger', 'All fields are required'));
				}

				let phones = getPhones();
				if (phones.find(el => el.startsWith(' ') || el.endsWith(' ')) !== undefined) {
					return alerts.appendChild(bAlert('danger', 'Both fields of phone are required'));
				}

				let emails = getEmails();
				if (emails.find(el => el == '') !== undefined) {
					return alerts.appendChild(bAlert('danger', 'Some email field is empty'));
				} else if (emails.find(el => !emailRegex.test(el)) !== undefined) {
					return alerts.appendChild(bAlert('danger', 'Some email field has not a valid format'));
				}

				let notice = bAlert('secondary', 'Sending phones request...');
				alerts.appendChild(notice);
				for (var i = 0; i < phones.length; i++) {
					const req = await fetch("{% url 'api:client_phones' %}", {
						method: 'POST',
						headers: new Headers({
							'Content-Type': 'application/json',
							'X-CSRFToken': form.csrfmiddlewaretoken.value
						}),
						body: JSON.stringify({
							id: parseInt(form.id.value),
							phone: phones[i],
						})
					}).then(out => out.json());

					if (req.error !== undefined) {
						return alerts.appendChild(bAlert('danger', `Error: ${req.error}`));
					}
				}
				notice.children[1].click();

				notice = bAlert('secondary', 'Sending emails request...');
				alerts.appendChild(notice);
				for (var i = 0; i < emails.length; i++) {
					const req = await fetch("{% url 'api:client_emails' %}", {
						method: 'POST',
						headers: new Headers({
							'Content-Type': 'application/json',
							'X-CSRFToken': form.csrfmiddlewaretoken.value
						}),
						body: JSON.stringify({
							id: parseInt(form.id.value),
							email: emails[i],
						})
					}).then(out => out.json());

					if (req.error !== undefined) {
						return alerts.appendChild(bAlert('danger', `Error: ${req.error}`));
					}
				}
				notice.children[1].click();

				notice = bAlert('secondary', 'Sending request...');
				alerts.appendChild(notice);

				const req = await fetch("{% url 'api:clients' %}", {
					method: 'PUT',
					headers: new Headers({
						'Content-Type': 'application/json',
						'X-CSRFToken': form.csrfmiddlewaretoken.value
					}),
					body: JSON.stringify({
						id: parseInt(form.id.value),
						firstName: form.firstname.value,
						secondName: (form.secondname.value != '')? form.secondname.value : undefined,
						firstLastName: form.firstlastname.value,
						secondLastName: (form.secondlastname.value != '')? form.secondlastname.value : undefined,
						country: form.country.value,
						state: form.state.value,
						city: form.city.value,
						age: form.age.value,
					})
				}).then(out => out.json());

				notice.children[1].click();
				if (req.error !== undefined) {
					return alerts.appendChild(bAlert('danger', `Error: ${req.error}`));
				}

				window.location.replace("{% url 'core:clients' %}");
			});
		})
	</script>
{% endblock %}

templates/rooms.html
{% extends "commons/base.html" %}

{% block title %}Rooms{% endblock %}

{% block body %}
	{% include "core/navbar.html" %}
	<div class="container" style="margin-top: 1em;">
		<a href="{% url 'core:create_headquarter' %}" class="btn btn-secondary">Create a Headquarter</a>
		<a href="{% url 'core:create_room' %}" class="btn btn-primary">Create a Room</a>
		<hr>
		<div id="rooms">
			<h1 v-if="!loaded" class="text-center">Loading...</h1>
			<div v-else>
				<input type="text" class="form-control" v-model="search" placeholder="Search">
				<br>
				<h1 v-if="rooms.length == 0">No rooms created.</h1>
				<table v-else class="table table-hover">
					<thead>
						<tr>
							<th>ID</th>
							<th>HQ Name</th>
							<th>Room Name</th>
							<th>Country</th>
							<th>State</th>
							<th>City</th>
							<th>Location Detail</th>
							<th>Floor</th>
							<th>Capacity</th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="room in rooms">
							<td>
								<pre>[[ room.hqId ]]-[[ room.id ]]</pre>
							</td>
							<td>[[ room.hqName ]]</td>
							<td>[[ room.name ]]</td>
							<td>[[ room.country ]]</td>
							<td>[[ room.state ]]</td>
							<td>[[ room.city ]]</td>
							<td>
								<textarea rows="2" readonly v-model="room.locationDetail"></textarea>
							</td>
							<td>[[ room.floor ]]</td>
							<td>[[ room.maxCapacity ]]</td>
						</tr>
					</tbody>
					<tfoot v-show="rooms.length > 100">
						<tr>
							<th>ID</th>
							<th>HQ Name</th>
							<th>Room Name</th>
							<th>Country</th>
							<th>State</th>
							<th>City</th>
							<th>Location Detail</th>
							<th>Floor</th>
							<th>Capacity</th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
	<script src="https://unpkg.com/vue@3.0.11/dist/vue.global.js"></script>
	<script type="module">
		Vue.createApp({
			delimiters: ['[[', ']]'],
			setup() {
				const _rooms = Vue.ref([]);
				const loaded = Vue.ref(false);
				const search = Vue.ref('');

				Vue.onMounted(async () => {
					_rooms.value = await fetch("{% url 'api:rooms' %}").then(out => out.json());

					loaded.value = true;
				});

				const rooms = Vue.computed(() => _rooms.value.filter(el => {
					const regex = new RegExp(search.value, 'i')
					return regex.test(el.hqName) || regex.test(el.name);
				}));

				return {
					loaded,
					rooms,
					search
				};
			}
		}).mount('#rooms')
	</script>
{% endblock %}